### ISSUE TITLE
Make reflexives work

### ISSUE THREAD

**Issue by jopetty** [clay-lab/logos#1]
Right now, the definition for the single reflexive 'Himself' is not parsed correctly. We should fix that.

**Comment by bobfrank1** [comment]
I just realized that the semantics being used for transitive verbs isn't compatible with the semantic interpretation of reflexives I was assuming without changing the VP rule. The reason is that the type of the quantifier (<<e,t>,t>) is different from the type needed for the reflexive (<<e,<e,t>>,<e,t>>). So, it looks like we'll need a special rule for the combination of the verb and reflexive, though we can probably come up with a denotation for the reflexive that will work with the verb interpretation we have.

**Comment by bobfrank1** [comment]
Here's the meaning we need for the object reflexive: 
((λV.(λz. ((V (λQ.(Q z))) z)))
Or in the notation used in the grammar:
Refl[SEM = <\V z.((V (\Q.(Q(z))) z) >] -> 'Himself'
The only trick is that this needs to be the function that applies to the verb, so we'll need a VP rule that looks like:
VP[SEM = <?obj(?v)>] ->TV[SEM = ?v] Refl[SEM = ?obj]
One advantage is that we don't need another verb meaning. If we allow ourselves a different verb meaning, we could go with a simpler reflexive meaning, but that would introduce other complications.

**Comment by jopetty** [comment]
Brilliant. One question I had: Since we modify the VP rule for reflexives to be
```
VP[SEM = <?obj(?v)>] 
```
where the object is being applied to the verb, and our S rule has something simiar:
```
S[SEM = <?subj(?vp)>]
```
might it make sense to try and change the regular VP rule as well to conform to this? I.e., make it something like `VP[SEM = <?obj(?v)>]` instead of the current `VP[SEM = <?v(?obj)>]`? That way we could combine the two rules into a single rule with an `OR / |`. I tried playing around with this a little bit, but I couldn't quite get it to work.

**Comment by jopetty** [comment]
The remaining work to do is to get gender agreement working in the reflexive so that it can generalize to any subject NP.

**Comment by jopetty** [comment]
Agreement is fixed in 2f8d561824cb0e84383e48a680c81fe04da57328.
